services:
  database:
    image: "postgres:alpine"
    env_file: 
      - ../.env
    ports: 
      - 5432:5432
    volumes:
      - pgclientsdata:/var/lib/postgresql/data

volumes:
  pgclientsdata:
    external: false